#!/usr/bin/env sh
# Usage:
#   bypass-cloudflare add
#   bypass-cloudflare del

ranges=$(curl -s https://www.cloudflare.com/ips-v4)
gateway=$(ip route show | grep default | awk '{print $3}')
set -ex
operation=$1
for range in $ranges; do
  sudo ip route $operation $range via $gateway
done
