#!/usr/bin/env sh
# Usage: chnroute /etc/config/chnroute
set -e
tmp=/tmp/chnroute.txt
dist=$1
#curl 'https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' >$tmp
curl 'https://mirrors.crzidea.com/http/ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' >$tmp
#curl 'https://download.microsoft.com/download/B/2/A/B2AB28E1-DAE1-44E8-A867-4987FE089EBE/msft-public-ips.csv' | awk -F ',' '/\./ { print $1 }' >>$tmp
#curl 'https://www.cloudflare.com/ips-v4' >>$tmp
# resolver1.opendns.com
curl 'https://ip-history.crzidea.com/?name=resolver1.opendns.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=resolver2.opendns.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=resolver3.opendns.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=resolver4.opendns.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
# xboxlive
curl 'https://ip-history.crzidea.com/?name=xsts.auth.xboxlive.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=xccs.xboxlive.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=userpresence.xboxlive.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
curl 'https://ip-history.crzidea.com/?name=uks.gssv-play-prodxhome.xboxlive.com' | grep -v '\.$' | sed 's/$/\/24/g' >>$tmp
sudo mv $tmp $dist
