#!/usr/bin/env bash
# Usage:
#   Add env in `~/.ddhs` as following:
#
#   ```
#   zone_id=
#   dns_recard_id=
#   auth_email=
#   auth_key=
#   name=
#   ```
#
#   Then run `ddns`
which dig >/dev/null
if [[ $? -ne 0 ]]; then
  sudo apt install -y dnsutils
fi

set -e

#ip=$(curl -s https://api.ipify.org)
ip=$(dig +short myip.opendns.com @resolver1.opendns.com)

vars=${1:-$HOME/.local/etc/ddns}
source $vars

data='{"type":"A","name":"${name}","content":"${ip}","ttl":120,"proxied":false}'
data=${data//$\{ip\}/$ip}
data=${data//$\{name\}/$name}

curl -sS -X PUT "https://api.cloudflare.com/client/v4/zones/${zone_id}/dns_records/${dns_recard_id}" \
     -H "X-Auth-Email: $auth_email" \
     -H "X-Auth-Key: $auth_key" \
     -H "Content-Type: application/json" \
     --data $data
echo
