#!/usr/bin/env sh
# Usage: dnsmasq-conf-generate 127.0.0.1#5300
SAFE_DNS=$1
#curl https://data.iana.org/TLD/tlds-alpha-by-domain.txt | tail -n +2 | grep -E '^[A-Z]{1,3}$' | tr '[:upper:]' '[:lower:]' | sed 's/^/server=\//' | sed "s/$/\/$SAFE_DNS/"
curl https://data.iana.org/TLD/tlds-alpha-by-domain.txt | tail -n +2 | sed 's/^CN$//' | grep -E '^[A-Z]' | tr '[:upper:]' '[:lower:]' | sed 's/^/server=\//' | sed "s/$/\/$SAFE_DNS/"
curl https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf | sed 's/114.114.114.114/#/'
#curl https://raw.githubusercontent.com/mawenjian/china-cdn-domain-whitelist/master/china-cdn-domain-whitelist.txt | grep -E '^[0-9a-z]' | sed 's/^/server=\//' | sed "s/$/\/#/"
