#!/usr/bin/env sh
git filter-branch --force --index-filter \
  "git rm --cached --ignore-unmatch $1" \
  --prune-empty --tag-name-filter cat -- --all
echo 'Done! Remember run `git push --force --all` to rewrite remote repo'
