#!/usr/bin/env sh
dir=$1
shift 1
cmd=$*

if [[ "Darwin" == `uname` ]]; then
  watcher="fswatch -1 $dir --exclude .git"
else
  watcher="inotifywait $dir -r -q -e close_write --exclude .git"
fi

until false; do
  clear
  $cmd &
  $watcher
  kill -9 $!
done
