#!/usr/bin/env sh
dir=$1
shift 1
cmd=$*
exclude="\/\..+"

if [[ "Darwin" == `uname` ]]; then
  watcher="fswatch -1 $dir -l 0.1 --exclude $exclude -E"
else
  watcher="inotifywait $dir -r -q -e close_write --exclude $exclude"
fi

until false; do
  clear
  $cmd &
  $watcher
  kill -9 $!
done
