#!/usr/bin/env bash
. ~/.local/etc/nicehash
mkdir -p ~/.nicehash
cd ~/.nicehash
killall ethminer
worker=${HOSTNAME/\.*/}
nohup ~/.local/bin/ethminer --opencl \
  --stratum-protocol 2 \
  --stratum daggerhashimoto.$location.nicehash.com:3353 \
  --userpass $address.$worker.x \
  1>eth.log 2>&1 &
