#!/usr/bin/env bash
# install nvm
if [[ -d ~/.nvm ]]; then
  echo "nvm was already installed."
  cd ~/.nvm
  git fetch origin
else
  echo "install nvm"
  git clone https://github.com/creationix/nvm.git ~/.nvm
  cd ~/.nvm
fi

git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`

# save PREFIX
prefix_save=$PREFIX
unset PREFIX

source ~/.nvm/nvm.sh
nvm install stable
echo `nvm version` >~/.nvmrc

# restore PREFIX
PREFIX=$prefix_save
