#!/usr/bin/env bash
# install nvm
: ${NVM_DIR:=$HOME/.nvm}

if [[ -d $NVM_DIR ]]; then
  echo "nvm was already installed."
  cd $NVM_DIR
  git fetch origin
else
  echo "install nvm"
  git clone https://github.com/creationix/nvm.git $NVM_DIR
  cd $NVM_DIR
fi

git checkout `git describe --abbrev=0 --tags --match "v[0-9]*" origin`

# save PREFIX
prefix_save=$PREFIX
unset PREFIX

source $NVM_DIR/nvm.sh
nvm install stable
echo `nvm version` >~/.nvmrc

# restore PREFIX
PREFIX=$prefix_save
