#!/usr/bin/env sh
# Usage:
#   openvpn-add-client client1
set -ex
client=$1

if [ ! -e keys/$client.key ]; then
  . ./vars
  ./pkitool $client
fi


dist_dir=dist/$client
mkdir -p $dist_dir
cp keys/ca.crt $dist_dir
cp keys/$client.key $dist_dir/client.key
cp keys/$client.crt $dist_dir/client.crt
cp client.ovpn $dist_dir/client.ovpn
