#!/usr/bin/env sh
# Usage:
#   openssl-gencert localhost
# This script depends ~/.openssl.cnf, download example from:
#   https://github.com/crzidea/confbook/blob/master/.openssl.cnf
# Inspired by:
#   https://nodejs.org/api/tls.html#tls_tls_ssl_concepts
set -e
workdir=$PWD
ca_dir="$HOME/.ca"

if [[ -d $ca_dir ]]; then
  echo $ca_dir exists
  >$ca_dir/index.txt
else
  mkdir -p $ca_dir
  cd $ca_dir
  mkdir -p newcerts private
  touch index.txt
  echo 00 >serial
  openssl genrsa -out private/cakey.pem 2048
  openssl req \
    -new -sha256 \
    -key private/cakey.pem \
    -subj "/CN=${USER}@${HOSTNAME} Root CA" \
    -out cacsr.pem
  openssl x509 -req \
    -in cacsr.pem \
    -signkey private/cakey.pem \
    -days 3650 \
    -out cacert.pem
fi

common_name=$1
mkdir -p $workdir/$common_name
cd $workdir/$common_name
openssl genrsa -out key.pem 2048
openssl req -new -sha256 -key key.pem -out csr.pem -subj "/CN=${common_name}"
openssl ca -batch -config $HOME/.openssl.cnf -in csr.pem -out ./cert.pem
