#!/usr/bin/env bash
cd "$(dirname "$0")"
git config remote.origin.url git@github.com:crzidea/local-bin.git
git pull
df -h

sudo swapoff -a
sudo rm /swapfile
ulimit -n 65535
docker system prune -f
docker container prune -f
docker image prune -f
docker volume prune -f
docker network prune -f
docker ps -aq | xargs docker inspect --format='{{.LogPath}}' | xargs sudo truncate -s 0
sudo systemctl stop docker
sudo systemctl stop warp-svc
sudo apt autoremove -y
sudo apt update
sudo apt upgrade -y
sudo systemctl start docker
sudo systemctl start warp-svc
#journalctl --vacuum-size=100m
journalctl --vacuum-size=100000000
#sudo journalctl --vacuum-size=100m
sudo journalctl --vacuum-size=100000000
sudo rm /var/log/*.log.*.gz
sudo rm /var/lib/cloudflare-warp/crash_reports/*
npm cache clean --force

df -h

# Reconnect warp
warp-cli disconnect
warp-cli connect
