#!/usr/bin/env bash
sudo swapoff -a
sudo rm /swapfile
ulimit -n 65535
docker system prune -f
docker container prune -f
docker image prune -f
docker volume prune -f
docker network prune -f
docker ps -aq | xargs docker inspect --format='{{.LogPath}}' | xargs sudo truncate -s 0
sudo apt update
sudo apt upgrade -y
sudo apt autoremove -y
#journalctl --vacuum-size=100m
journalctl --vacuum-size=100000000
#sudo journalctl --vacuum-size=100m
sudo journalctl --vacuum-size=100000000
sudo rm /var/log/*.log.*.gz
sudo apt autoremove -y
sudo rm /var/lib/cloudflare-warp/crash_reports/*
npm cache clean --force

df -h
